apiVersion: v1
kind: Service
metadata:
    name: joshmgross-azurevotingappredis
spec:
    type: LoadBalancer
    ports:
    - port: 80 
    selector:
        app: joshmgross-azurevotingappredis